config/routes.rb
FlashCard::Application.routes.draw do
  root to: 'decks#index'

  get "cards/create"
  get "cards/destroy"
  resources :decks do
    resources :cards
  end
end

app/models/card.rb
class Card < ActiveRecord::Base
belongs_to :deck
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  has_many :cards
  accepts_nested_attributes_for :cards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def create                                            
    @deck = Deck.find(params[:deck_id])
    @card = @deck.cards.build(card_params)
    
    if @card.description.empty?
      @card.description = get_definition
    end
    @card.save
    redirect_to @deck
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    redirect_to @card.deck
  end

  def card_params
    params.require(:card).permit(:title, :description, :deck_id)
  end

  def get_definition
    Wordnik.word.get_definitions(params[:title])
  end

end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show, :edit, :update, :destroy]

def format_description(card)
    line_a = []
    word_a = card.description.split(' ')
    line = ''
    last = word_a.size - 1
    word_a.each_with_index do |word, i|
      if line.length + word.length > 80
        line_a.push(line)
        line = ''
      elsif i == last
        line += ' ' + word
        line_a.push(line)
      else
        line += ' ' + word
      end
    end
    line_a
  end
  helper_method :format_description

  # GET /decks
  # GET /decks.json
  def index
    @decks = Deck.all
  end

  # GET /decks/1
  # GET /decks/1.json
  def show
    @deck
  end

  # GET /decks/new
  def new
    @deck = Deck.new
  end

  # GET /decks/1/edit
  def edit
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = Deck.new(deck_params)

    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
        format.json { render action: 'show', status: :created, location: @deck }
      else
        format.html { render action: 'new' }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1
  # PATCH/PUT /decks/1.json
  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck.destroy
    respond_to do |format|
      format.html { redirect_to decks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deck
      @deck = Deck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deck_params
      params.require(:deck).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/cards/create.html.erb
<h1>Cards#create</h1>
<p>Find me in app/views/cards/create.html.erb</p>

app/views/cards/destroy.html.erb
<h1>Cards#destroy</h1>
<p>Find me in app/views/cards/destroy.html.erb</p>

app/views/decks/_edit_form.html.erb
<%= form_for(@deck) do |f| %>
  <% if @deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
      <% @deck.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field handwritten form-control">
    <%= f.text_field :name %>
  </div>
  <div class="actions pull-right">
    <%= f.submit "Update Deck", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/decks/_form.html.erb
<%= form_for(@deck) do |f| %>
  <% if @deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
      <% @deck.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field handwritten form-control">
    <%= f.text_field :name %>
  </div>
  <div class="actions pull-right">
    <%= f.submit "Create Deck", :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/decks/edit.html.erb
<div class="jumbotron btn-group">
<h2 class="handwritten" >Edit Deck</h2>

<%= render 'edit_form' %>
</div>

app/views/decks/index.html.erb
<section class="card shadow center">
    <h1 class="card-header center">Available Decks</h1>
    <% @decks.each do |deck| %> 
      <h4 class="card-row">
          <%= link_to deck.name, deck %> 
          <%= link_to 'Delete', deck, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-mini pull-right" %>
            <%= link_to 'Edit', edit_deck_path(deck), :class => "btn btn-mini pull-right" %>

    </h4>
  <% end %>
</section>
<br>
<footer class="handwritten">
      <%= link_to 'New Deck', new_deck_path, :class => "btn btn-large btn-primary width-card" %>
</footer>

app/views/decks/new.html.erb
<div class="jumbotron btn-group">
<h2 class="handwritten" >Create a new Deck</h2>

<%= render 'form' %>
</div>

app/views/decks/show.html.erb
<header>
	<h1 class="center handwritten"> <%= @deck.name %> </h1>
	    <div class="btn-group">
			<%= link_to 'Back', decks_path, :class => "btn btn-primary btn-large" %>
			<%= link_to 'Edit', edit_deck_path(@deck), :class => "btn btn-large"%>
			<%= link_to 'Delete', @deck, :method => :delete, :confirm => "Are you sure?", :class => "btn btn-large" %>
		</div>
	<p id="notice"><%= notice %></p>
</header>
<hr>
<section>
	<h2 class="handwritten">Add Card</h2>
	<%= form_for [@deck, @deck.cards.build], :html => {:class => 'form-inline'} do |f| %>
		<%= f.label :title, "Word:" %>
		<%= f.text_field :title  %>
		<%= f.label :description, "Description:" %>
		<%= f.text_field :description %>
		<%= f.submit "Add Card", :class => "btn btn-primary" %>
	<% end %>
</section>

<br>

<% @deck.cards.each do |card| %>
	<% unless card.title == nil	 %>
		<article class="card shadow center">
		    <h1 class="card-header center"> <%= card.title %></h1>
			<% card_a = format_description(card) %>
			
			<% card_a.each do |line| %>
				<p class="card-row">
					<%= line %>
				</p>
			<% end %>
			<div class="pull-right margin-2-per">
				<%= link_to "Delete Card", [@deck, card], :method => :delete, :confirm => "Are your sure?", :class => "btn btn-default"  %>
			</div>
		</article>
		<br>
		<hr>
		<br>
	<% end %>	
<% end %>

<br>

<footer>
      <%= link_to 'Back', decks_path, :class => "btn btn-primary btn-large width-card" %>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flash Card : Study Helper</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render "shared/shiv" %>
</head>
<body>
<%= render "shared/nav" %>
<div style="width:80%;" class="container center drop-50">
<%= yield %>
<br>
<hr>
<br>
<%= debug(params) if Rails.env.development? %>
<%= render "shared/jsinclude" %>
</div>
</body>
</html>

app/views/shared/_jsinclude.html.erb
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="//code.jquery.com/jquery.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>

app/views/shared/_nav.html.erb
<header class="navbar width-80">
  <div class="navbar-inner">
    <div class="container">
    <div class="brand handwritten" >
			<%= link_to "Flash Card", root_path %>
		</div>
      <nav class="handwritten">
        <ul class="nav pull-right">
          <li><%= link_to "Home",    root_path %></li>
          <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">New Deck <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><%= link_to "New Deck", new_deck_path %></li>
                <li class="divider"></li>
                <li><%= link_to "All Decks", root_path %></li>
              </ul>
            </li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/shared/_shiv.html.erb
<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->